name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Mocha Tests and Save Results
        run: |
          npm run check > test-results.txt || true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./artifacts

      - name: Display Test Results
        run: cat ./artifacts/test-results.txt

      - name: Install Dependencies
        run: npm install

      - name: Install PM2
        run: npm install -g pm2

      - name: Deploy Application with PM2
        run: |
          echo "Starting Node.js application with PM2..."
          pm2 start npm --name "ostad-app" -- start
          pm2 save
          pm2 status